### ISSUE TITLE
[ODOO17] Couldn't bind the websocket. Is the connection opened on the evented port (8072)?

### ISSUE THREAD

**Issue by szabolcsmaj** [odoocker/odoocker#10]
I'm trying to make this work with Odoo 17 but I'm getting this error:

```odoo_1         | 2023-11-27 22:39:55,071 12 ERROR odoo odoo.http: Exception during request handling. 
odoo_1         | Traceback (most recent call last):
odoo_1         |   File "/usr/lib/python3/dist-packages/odoo/addons/bus/websocket.py", line 837, in open_connection
odoo_1         |     socket = request.httprequest.environ['socket']
odoo_1         | KeyError: 'socket'
odoo_1         | 
odoo_1         | The above exception was the direct cause of the following exception:
odoo_1         | 
odoo_1         | Traceback (most recent call last):
odoo_1         |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 2157, in __call__
odoo_1         |     response = request._serve_db()
odoo_1         |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1732, in _serve_db
odoo_1         |     return service_model.retrying(self._serve_ir_http, self.env)
odoo_1         |   File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
odoo_1         |     result = func()
odoo_1         |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1759, in _serve_ir_http
odoo_1         |     response = self.dispatcher.dispatch(rule.endpoint, args)
odoo_1         |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1873, in dispatch
odoo_1         |     return self.request.registry['ir.http']._dispatch(endpoint)
odoo_1         |   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 207, in _dispatch
odoo_1         |     result = endpoint(**request.params)
odoo_1         |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 722, in route_wrapper
odoo_1         |     result = endpoint(self, *args, **params_ok)
odoo_1         |   File "/usr/lib/python3/dist-packages/odoo/addons/bus/controllers/websocket.py", line 23, in websocket
odoo_1         |     return WebsocketConnectionHandler.open_connection(request)
odoo_1         |   File "/usr/lib/python3/dist-packages/odoo/addons/bus/websocket.py", line 849, in open_connection
odoo_1         |     raise RuntimeError(
odoo_1         | RuntimeError: Couldn't bind the websocket. Is the connection opened on the evented port (8072)?
```

I tried a few tweaks here and there in the nginx configuration, but nothing is working so far.

Anyone there, who managed to fix this?

**Comment by ppsaheed** [comment]
try https://github.com/ppsaheed/odoocker/tree/17.0

```
APP_ENV=production
INIT=
UPDATE=
LOAD=base,web
ROOT_PATH=/usr/lib/python3/dist-packages/odoo
WORKERS=2
DEV_MODE=reload,xml
DOMAIN=erp.odoocker.test
ADMIN_PASSWD=odoo

# Services
PROJECT_NAME=odoocker
SERVICES=odoo,nginx,proxy,postgres,acme,keydb

# Service configuration
USE_REDIS=true
USE_S3=false
USE_SENTRY=false
USE_PGADMIN=false

continue .env

```

**Comment by yhaelopez** [comment]
@szabolcsmaj @ppsaheed I really want to thank you guys for using Odoocker and spot this issues and contribute.

Odoocker offical branch 17.0 is out now. I explain a bit more here: https://github.com/odoocker/odoocker/issues/9

Let me know if this setup fixes your issue so I can close this.

**Comment by yhaelopez** [comment]
Closing as it's resolved here: https://github.com/odoocker/odoocker/issues/9
